name: animeshnik
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  dio: 5.7.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  video_player_control_panel: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    # - assets/images/
